#!/usr/bin/env python3
# Copyright (c) 2026 The DeFCoN Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""One peer cannot spend this node's CPU on DSL gossip without limit.

The three DSL messages (poseresp, posereport, posechal) had no peer accounting
of any kind: no rate limit, and no path to Misbehaving either, because
ProcessDSLMessage returns void and so cannot be scored through
ProcessPeerMsgRet. A failed verification is never remembered -- the dedup maps
record only ACCEPTED items -- so one real proTxHash carrying a wrong signature
passes the filter for as long as the sender keeps sending it, and every copy
costs a BLS pairing (2.49 ms measured on this tree).

The fix is a per-peer budget charged at the entry of ProcessDSLMessage, before
any deserialization, so it covers all three types and precedes the expensive
step. What this test has to prove is both halves of it, and the second matters
more than the first: a budget too tight would throttle honest gossip, and that
failure looks exactly like the lost epoch the Sentinel layer has been chasing
since #207 -- it would be worse than the hole it closes.

  1. a peer that has just connected is handed one epoch's honest ceiling and
     no more, so dropping the connection and coming back is not a way to be
     handed the whole cap again
  2. an ordinary honest epoch passes untouched. One peer delivers
     N + N * nDSLSentinelCount messages over an epoch -- every masternode
     announces once, EmitReports files a report for every assigned target
     whether it answered or not, and the flood forwards each message once per
     peer. That is not a rare worst case: measured on the devnet, one peer's
     epoch was 152 announcements and 1064 reports, exactly N and N * 7, while
     the commitments for the same window recorded nobody missing. This test
     takes that figure, 152 * 8 = 1216 in a single epoch with no block mined in
     between, and drops none of them
  3. the budget is where the code says it is: the same peer is cut off at the
     cap, DSL_MSG_BUDGET_CAP_EPOCHS epochs' worth, and not before
  4. it refills with the CHAIN, not the clock: one block returns exactly one
     block's share and no more. Honest DSL traffic is generated by the tick of
     a block, so a clock-based refill would be wrong in both directions -- on
     this regtest a whole epoch passes in under a second of wall clock
  5. the budget is one per peer and not one per message type: a peer that has
     spent its ceiling on announcements cannot then send a report either, while
     a peer that has spent nothing can
  6. a message that cannot be read is scored, and ten of them are a
     discouragement. A message that reads but is rejected is not scored: after
     a reorg the epoch's base changes and honest announcements in flight are
     signed against the old one, so they fail legitimately

Closes F-2026-131 and, one layer down, the mechanism of F-2026-122.
"""

import struct

from test_framework.messages import ser_uint256
from test_framework.p2p import MESSAGEMAP, P2PInterface
from test_framework.test_framework import BitcoinTestFramework
from test_framework.util import assert_equal

EPOCH_INTERVAL = 24        # Consensus::Params::nDSLEpochInterval
SENTINELS = 7              # Consensus::Params::nDSLSentinelCount
MIN_MNS = 64               # DSL_MSG_BUDGET_MIN_MNS
CAP_EPOCHS = 4             # DSL_MSG_BUDGET_CAP_EPOCHS
REFILL_EPOCHS = 2          # DSL_MSG_BUDGET_REFILL_EPOCHS
# This network has no masternodes, so the floor is what sizes the budget.
CEILING = MIN_MNS * (1 + SENTINELS)               # honest messages per peer per epoch
BUDGET = CAP_EPOCHS * CEILING                     # what a peer may hold in hand at once
PER_BLOCK = REFILL_EPOCHS * CEILING // EPOCH_INTERVAL      # whole messages one block returns
BLOCKS_TO_CAP = CAP_EPOCHS * EPOCH_INTERVAL // REFILL_EPOCHS  # blocks from empty to the cap
# The devnet the layer actually runs on: 152 masternodes, each announcing once
# and reportable by SENTINELS sentinels. This is the number that must never be
# throttled, and it is deliberately not derived from the constants above.
DEVNET_HONEST_EPOCH = 152 * (1 + SENTINELS)  # 1216

UNREADABLE_SCORE = 10      # DSL_MSG_MISBEHAVING_UNREADABLE
DISCOURAGEMENT = 100       # DISCOURAGEMENT_THRESHOLD
BLS_SIG_SIZE = 96

EXHAUSTED = "per-peer budget exhausted"


class msg_poseresp:
    """CPoSeServiceResponse on the wire: nEpoch, proTxHash, a basic-scheme BLS
    signature."""
    __slots__ = ("nEpoch", "proTxHash", "sig")
    msgtype = b"poseresp"

    def __init__(self, nEpoch=0, proTxHash=0, sig=None):
        self.nEpoch = nEpoch
        self.proTxHash = proTxHash
        self.sig = b"\x00" * BLS_SIG_SIZE if sig is None else sig

    def deserialize(self, f):
        self.nEpoch = struct.unpack("<I", f.read(4))[0]
        self.proTxHash = int.from_bytes(f.read(32), "little")
        self.sig = f.read(BLS_SIG_SIZE)

    def serialize(self):
        return struct.pack("<I", self.nEpoch) + ser_uint256(self.proTxHash) + self.sig

    def __repr__(self):
        return "msg_poseresp(nEpoch=%d, proTxHash=%064x)" % (self.nEpoch, self.proTxHash)


class msg_posereport:
    """CPoSeServiceReport on the wire: nEpoch, target, sentinel, status, sig."""
    __slots__ = ("nEpoch", "target", "sentinel", "status", "sig")
    msgtype = b"posereport"

    def __init__(self, nEpoch=0, target=0, sentinel=0, status=2):
        self.nEpoch = nEpoch
        self.target = target
        self.sentinel = sentinel
        self.status = status
        self.sig = b"\x00" * BLS_SIG_SIZE

    def deserialize(self, f):
        self.nEpoch = struct.unpack("<I", f.read(4))[0]
        self.target = int.from_bytes(f.read(32), "little")
        self.sentinel = int.from_bytes(f.read(32), "little")
        self.status = struct.unpack("<B", f.read(1))[0]
        self.sig = f.read(BLS_SIG_SIZE)

    def serialize(self):
        return (struct.pack("<I", self.nEpoch) + ser_uint256(self.target) + ser_uint256(self.sentinel)
                + struct.pack("<B", self.status) + self.sig)

    def __repr__(self):
        return "msg_posereport(nEpoch=%d)" % self.nEpoch


class msg_poseresp_truncated:
    """Four bytes short of an epoch number: nothing can read this."""
    msgtype = b"poseresp"

    def serialize(self):
        return b"\x01\x02"

    def __repr__(self):
        return "msg_poseresp_truncated()"


MESSAGEMAP[b"poseresp"] = msg_poseresp
MESSAGEMAP[b"posereport"] = msg_posereport


def junk_protx(i):
    # distinct per message, and none of them a masternode
    return (0xDEAD << 240) | i


class Quiet(P2PInterface):
    """Sends only."""
    def on_poseresp(self, message):
        pass

    def on_posereport(self, message):
        pass


class DSLMessageBudgetTest(BitcoinTestFramework):
    def set_test_params(self):
        self.num_nodes = 1
        self.setup_clean_chain = True
        self.extra_args = [[
            "-testactivationheight=dsl@1",
            # the DSL path sits in the producer's DIP3-active section, as on
            # every network that runs the layer
            "-dip3params=2:2",
            "-deprecatedrpc=banscore",
        ]]

    # -- helpers ----------------------------------------------------------
    def log_since(self, mark):
        with open(self.nodes[0].debug_log_path, encoding="utf-8") as fh:
            fh.seek(mark)
            return fh.read()

    def send_announcements(self, peer, epoch, first, count):
        for i in range(first, first + count):
            peer.send_message(msg_poseresp(epoch, junk_protx(i)))
        peer.sync_with_ping()

    def seen_and_dropped(self, mark, epoch):
        """(messages the node read, whether it reported a dropped one)"""
        log = self.log_since(mark)
        return log.count("DSL -- poseresp epoch=%d " % epoch), EXHAUSTED in log

    def newest_peer_id(self):
        """Node ids rise with every connection, so the one just added is the
        highest the node knows."""
        return max(info["id"] for info in self.nodes[0].getpeerinfo())

    def banscore(self, peer_id):
        for info in self.nodes[0].getpeerinfo():
            if info["id"] == peer_id:
                return info["banscore"]
        raise AssertionError("peer %d is gone from getpeerinfo" % peer_id)

    # -- the test ---------------------------------------------------------
    def run_test(self):
        node = self.nodes[0]

        # A tip on an epoch boundary, so the base block of the epoch the peer
        # names exists and its messages take the ordinary path rather than the
        # hold for early announcements. Nothing below depends on where they end
        # up: the budget is charged before any of that.
        self.generate(node, 2 * EPOCH_INTERVAL)
        epoch = node.getblockcount() // EPOCH_INTERVAL
        assert_equal(node.getblockcount() % EPOCH_INTERVAL, 0)

        peer = node.add_p2p_connection(Quiet())
        peer_id = self.newest_peer_id()

        self.log.info("A peer that has just connected holds one epoch's ceiling (%d), not the cap", CEILING)
        mark = node.debug_log_bytes()
        self.send_announcements(peer, epoch, 0, CEILING)
        seen, dropped = self.seen_and_dropped(mark, epoch)
        assert_equal(seen, CEILING)
        assert not dropped, "a fresh peer could not spend one epoch's ceiling"
        mark = node.debug_log_bytes()
        self.send_announcements(peer, epoch, CEILING, 20)
        seen, dropped = self.seen_and_dropped(mark, epoch)
        assert_equal(seen, 0)
        assert dropped, "a fresh peer was handed more than one epoch's ceiling"

        self.log.info("%d blocks fill it from empty to the cap (%d)", BLOCKS_TO_CAP, BUDGET)
        self.generate(node, BLOCKS_TO_CAP)
        epoch = node.getblockcount() // EPOCH_INTERVAL

        self.log.info("An honest devnet epoch from one peer (%d messages) is not throttled", DEVNET_HONEST_EPOCH)
        mark = node.debug_log_bytes()
        self.send_announcements(peer, epoch, 0, DEVNET_HONEST_EPOCH)
        seen, dropped = self.seen_and_dropped(mark, epoch)
        assert_equal(seen, DEVNET_HONEST_EPOCH)
        assert not dropped, "an honest epoch's worth of announcements was throttled"

        self.log.info("The rest of the budget (%d more) is spent without a drop", BUDGET - DEVNET_HONEST_EPOCH)
        mark = node.debug_log_bytes()
        self.send_announcements(peer, epoch, DEVNET_HONEST_EPOCH, BUDGET - DEVNET_HONEST_EPOCH)
        seen, dropped = self.seen_and_dropped(mark, epoch)
        assert_equal(seen, BUDGET - DEVNET_HONEST_EPOCH)
        assert not dropped, "the budget bound before its stated size"

        self.log.info("Past it, with no block mined, every further message is dropped unread")
        mark = node.debug_log_bytes()
        self.send_announcements(peer, epoch, BUDGET, 100)
        seen, dropped = self.seen_and_dropped(mark, epoch)
        assert_equal(seen, 0)
        assert dropped, "the budget did not bind at all"

        self.log.info("One block returns exactly one block's share (%d) and no more", PER_BLOCK)
        self.generate(node, 1)
        mark = node.debug_log_bytes()
        self.send_announcements(peer, epoch, BUDGET + 100, PER_BLOCK + 20)
        seen, dropped = self.seen_and_dropped(mark, epoch)
        assert_equal(seen, PER_BLOCK)
        assert dropped

        self.log.info("And blocks return the whole budget again")
        self.generate(node, BLOCKS_TO_CAP)
        next_epoch = node.getblockcount() // EPOCH_INTERVAL
        mark = node.debug_log_bytes()
        self.send_announcements(peer, next_epoch, 0, DEVNET_HONEST_EPOCH)
        seen, dropped = self.seen_and_dropped(mark, next_epoch)
        assert_equal(seen, DEVNET_HONEST_EPOCH)
        assert not dropped

        self.log.info("One budget per peer, shared by every DSL message type")
        epoch = node.getblockcount() // EPOCH_INTERVAL
        spent = node.add_p2p_connection(Quiet())
        self.send_announcements(spent, epoch, 0, CEILING)
        fresh = node.add_p2p_connection(Quiet())
        mark = node.debug_log_bytes()
        for who in (spent, fresh):
            who.send_message(msg_posereport(epoch, junk_protx(1), junk_protx(2)))
            who.sync_with_ping()
        # the report of the peer that spent its ceiling on announcements is
        # dropped; the one from a peer that has spent nothing is read
        assert_equal(self.log_since(mark).count("DSL -- posereport epoch=%d " % epoch), 1)

        self.log.info("A message that reads but is rejected is never scored")
        assert_equal(self.banscore(peer_id), 0)

        self.log.info("A message that cannot be read is scored %d, and ten are a discouragement", UNREADABLE_SCORE)
        junk = node.add_p2p_connection(Quiet())
        junk_id = self.newest_peer_id()
        for strike in range(1, DISCOURAGEMENT // UNREADABLE_SCORE):
            junk.send_message(msg_poseresp_truncated())
            junk.sync_with_ping()
            assert_equal(self.banscore(junk_id), strike * UNREADABLE_SCORE)
        with node.assert_debug_log(["DISCOURAGE THRESHOLD EXCEEDED"]):
            junk.send_message(msg_poseresp_truncated())
            junk.wait_for_disconnect()

        self.log.info("The peer that only sent rejected-but-readable messages is still connected")
        assert_equal(self.banscore(peer_id), 0)


if __name__ == "__main__":
    DSLMessageBudgetTest().main()
