// Copyright (c) 2025 The Defcon Developers
// Distributed under the MIT/X11 software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <pos/kernel.h>

/**
 * Check whether the coinstake timestamp mask has been adhered
 * to, preventing bruteforcing of the timestamp.
 */
bool CheckCoinStakeTimestamp(int nTimeBlock, const Consensus::Params& params)
{
    return ((nTimeBlock & params.posTimestampMask) == 0);
}

/**
 * Calculate PoS kernel weight for an interval of prior blocks:
 * Returns the sum of difficulty of a series of blocks over an interval
 * divided by the total time taken between blocks in the interval.
 */
double GetPoSKernelPS(CBlockIndex *pindex, const Consensus::Params& params)
{
    LOCK(cs_main);

    CBlockIndex *pindexPrevStake = nullptr;

    int nPoSInterval = 72;
    double dStakeKernelsTriedAvg = 0;
    int nStakesHandled = 0, nStakesTime = 0;

    while (pindex && nStakesHandled < nPoSInterval) {
        if (pindex->IsProofOfStake()) {
            if (pindexPrevStake) {
                dStakeKernelsTriedAvg += GetDifficulty(pindexPrevStake) * 4294967296.0;
                nStakesTime += pindexPrevStake->nTime - pindex->nTime;
                nStakesHandled++;
            }
            pindexPrevStake = pindex;
        }
        pindex = pindex->pprev;
    }

    double result = 0;

    if (nStakesTime)  {
        result = dStakeKernelsTriedAvg / nStakesTime;
    }

    result *= params.posTimestampMask + 1;

    return result;
}

/**
 * Stake Modifier (hash modifier of proof-of-stake):
 * The purpose of stake modifier is to prevent a txout (coin) owner from
 * computing future proof-of-stake generated by this txout at the time
 * of transaction confirmation. To meet kernel protocol, the txout
 * must hash with a future stake modifier to generate the proof.
 */
uint256 ComputeStakeModifier(const CBlockIndex* pindexPrev, const uint256& kernel)
{
    if (!pindexPrev)
        return uint256(); // genesis block's modifier is 0

    CDataStream ss(SER_GETHASH, 0);
    ss << kernel << pindexPrev->nStakeModifier;
    return Hash(ss);
}

/**
 * BlackCoin kernel protocol
 * coinstake must meet hash target according to the protocol:
 * kernel (input 0) must meet the formula
 *     hash(nStakeModifier + txPrev.block.nTime + txPrev.nTime + txPrev.vout.hash + txPrev.vout.n + nTime) < bnTarget * nWeight
 * this ensures that the chance of getting a coinstake is proportional to the
 * amount of coins one owns.
 * The reason this hash is chosen is the following:
 *   nStakeModifier: scrambles computation to make it very difficult to precompute
 *                   future proof-of-stake
 *   txPrev.block.nTime: prevent nodes from guessing a good timestamp to
 *                       generate transaction for future advantage,
 *                       obsolete since v3
 *   txPrev.nTime: slightly scrambles computation
 *   txPrev.vout.hash: hash of txPrev, to reduce the chance of nodes
 *                     generating coinstake at the same time
 *   txPrev.vout.n: output number of txPrev, to reduce the chance of nodes
 *                  generating coinstake at the same time
 *   nTime: current timestamp
 *   block/tx hash should not be used here as they can be generated in vast
 *   quantities so as to generate blocks faster, degrading the system back into
 *   a proof-of-work situation.
 */
bool CheckStakeKernelHash(const CBlockIndex* pindexPrev,
    uint32_t nBits, uint32_t nBlockFromTime,
    CAmount prevOutAmount, const COutPoint& prevout, uint32_t nTime,
    uint256& hashProofOfStake, uint256& targetProofOfStake,
    bool fPrintProofOfStake)
{
    if (nTime < nBlockFromTime) {
        LogPrint(BCLog::POS, "%s: nTime violation", __func__);
        return false;
    }

    arith_uint256 bnTarget;
    bool fNegative;
    bool fOverflow;

    bnTarget.SetCompact(nBits, &fNegative, &fOverflow);
    if (fNegative || fOverflow || bnTarget == 0) {
        LogPrint(BCLog::POS, "%s: SetCompact failed.", __func__);
        return false;
    }

    // Weighted target
    int64_t nValueIn = prevOutAmount;
    arith_uint256 bnWeight = arith_uint256(nValueIn);
    bnTarget *= bnWeight;

    targetProofOfStake = ArithToUint256(bnTarget);

    const uint256& nStakeModifier = pindexPrev->nStakeModifier;
    int nStakeModifierHeight = pindexPrev->nHeight;
    int64_t nStakeModifierTime = pindexPrev->nTime;

    CDataStream ss(SER_GETHASH, 0);
    ss << nStakeModifier;
    ss << nBlockFromTime << prevout.hash << prevout.n << nTime;
    hashProofOfStake = Hash(ss);

    if (fPrintProofOfStake) {
        LogPrint(BCLog::POS, "%s: using modifier=%s at height=%d timestamp=%s\n",
            __func__, nStakeModifier.ToString(), nStakeModifierHeight,
            FormatISO8601DateTime(nStakeModifierTime));
        LogPrint(BCLog::POS, "%s: check modifier=%s nTimeKernel=%u nPrevout=%u nTime=%u hashProof=%s\n",
            __func__, nStakeModifier.ToString(),
            nBlockFromTime, prevout.n, nTime,
            hashProofOfStake.ToString());
    }

    // Now check if proof-of-stake hash meets target protocol
    if (UintToArith256(hashProofOfStake) > bnTarget) {
        return false;
    }

    if (fPrintProofOfStake) {
        LogPrint(BCLog::POS, "%s: using modifier=%s at height=%d timestamp=%s\n",
            __func__, nStakeModifier.ToString(), nStakeModifierHeight,
            FormatISO8601DateTime(nStakeModifierTime));
        LogPrint(BCLog::POS, "%s: pass modifier=%s nTimeKernel=%u nPrevout=%u nTime=%u hashProof=%s\n",
            __func__, nStakeModifier.ToString(),
            nBlockFromTime, prevout.n, nTime,
            hashProofOfStake.ToString());
    }

    return true;
}

bool CheckProofOfStake(CChainState& chain_state, BlockValidationState& state, const CBlockIndex* pindexPrev, const CTransaction& tx, int64_t nTime, unsigned int nBits, uint256& hashProofOfStake, uint256& targetProofOfStake)
{
    if (!tx.IsCoinStake() || tx.vin.size() < 1) {
        return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "malformed-txn");
    }

    // Kernel (input 0) must match the stake hash target per coin age (nBits)
    const CTxIn& txin = tx.vin[0];

    Coin coin;
    {
        LOCK(cs_main);
        if (!chain_state.CoinsTip().GetCoin(txin.prevout, coin) || coin.IsSpent()) {
            return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "prevout-not-found");
        }
    }

    CBlockIndex* pindex = chain_state.m_chain[coin.nHeight];
    if (!pindex) {
        return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "invalid-prevout");
    }
    int64_t nBlockFromTime = pindex->GetBlockTime();

    int nRequiredDepth = COINBASE_MATURITY + 1;
    int nDepth = pindexPrev->nHeight - coin.nHeight;
    if (nRequiredDepth > nDepth) {
        LogPrint(BCLog::POS, "ERROR: %s: Tried to stake at depth %d\n", __func__, nDepth + 1);
        return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "bad-stake-depth");
    }

    CAmount amount = coin.out.nValue;
    const Consensus::Params& params = Params().GetConsensus();
    if (amount < params.stakeValueRange[0] || amount > params.stakeValueRange[1]) {
        LogPrint(BCLog::POS, "ERROR: %s: Stake input amount is out of range (amount %d, min %d, max %d)\n",
                             __func__, amount / COIN, params.stakeValueRange[0] / COIN, params.stakeValueRange[1] / COIN);
        return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "bad-stake-amount");
    }

    int64_t inputAge = nTime - nBlockFromTime;
    if (inputAge < params.stakeAgeRange[0] || inputAge > params.stakeAgeRange[1]) {
        LogPrint(BCLog::POS, "ERROR: %s: Stake input age is out of range (age: %d min: %d, max: %d)\n",
                             __func__, inputAge, params.stakeAgeRange[0], params.stakeAgeRange[1]);
        return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "bad-stake-age");
    }

    ScriptError serror = SCRIPT_ERR_OK;
    if (!VerifyScript(txin.scriptSig, coin.out.scriptPubKey, STANDARD_SCRIPT_VERIFY_FLAGS, TransactionSignatureChecker(&tx, 0, coin.out.nValue, MissingDataBehavior::ASSERT_FAIL), &serror)) {
        LogPrint(BCLog::POS, "ERROR: %s: verify-script-failed, txn %s, reason %s\n", __func__, tx.GetHash().ToString(), ScriptErrorString(serror));
        return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "bad-stake-signature");
    }

    if (!CheckStakeKernelHash(pindexPrev, nBits, nBlockFromTime, coin.out.nValue, txin.prevout, nTime, hashProofOfStake, targetProofOfStake)) {
        LogPrint(BCLog::POS, "ERROR: %s: Check kernel failed on coinstake %s, hashProof=%s\n", __func__, tx.GetHash().ToString(), hashProofOfStake.ToString());
        return state.Invalid(BlockValidationResult::BLOCK_CONSENSUS, "bad-stake-kernel");
    }

    return true;
}

// Used only when staking, not during validation
bool CheckKernel(CChainState& chain_state, const CBlockIndex* pindexPrev, unsigned int nBits, int64_t nTime, const COutPoint& prevout, int64_t* pBlockTime)
{
    Coin coin;
    {
        LOCK(cs_main);
        if (!chain_state.CoinsTip().GetCoin(prevout, coin))
            return false;
    }

    if (coin.IsSpent())
        return false;

    CBlockIndex* pindex = chain_state.m_chain[coin.nHeight];
    if (!pindex)
        return false;

    int nRequiredDepth = COINBASE_MATURITY + 1;
    int nDepth = pindexPrev->nHeight - coin.nHeight;

    if (nRequiredDepth > nDepth)
        return false;

    if (pBlockTime)
        *pBlockTime = pindex->GetBlockTime();

    CAmount amount = coin.out.nValue;
    uint256 hashProofOfStake, targetProofOfStake;
    return CheckStakeKernelHash(pindexPrev, nBits, *pBlockTime, amount, prevout, nTime, hashProofOfStake, targetProofOfStake);
}
