#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the dash network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,
};
static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x9a,0x1a,0x9b,0x42,0x4e,0x1f,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
