#!/usr/bin/env bash
#
#  defcond The DeFCoN Core server.
#
#
# chkconfig: 345 80 20
# description: defcond
# processname: defcond
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/defcond, see below
if [ -f /etc/sysconfig/defcond ]; then
        . /etc/sysconfig/defcond
fi

RETVAL=0

prog=defcond
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/defcond
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/defcond}

# defcond defaults to /usr/bin/defcond, override with BITCOIND_BIN
defcond=${BITCOIND_BIN-/usr/bin/defcond}

# defcond opts default to the same files and directories as the systemd unit,
# override with BITCOIND_OPTS
defcond_opts=${BITCOIND_OPTS--conf=/etc/defcon/defcon.conf -datadir=/var/lib/defcond -pid=/var/lib/defcond/defcond.pid -disablewallet}

# run as the defcon user, override with BITCOIND_USER
defcond_user=${BITCOIND_USER-defcon}

start() {
    echo -n $"Starting $prog: "
    daemon --user="$defcond_user" $DAEMONOPTS $defcond $defcond_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
